exclude: ".git|.tox"
default_stages: [commit]
fail_fast: true
default_language_version:
  python: python3

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: # arguments to configure flake8
        # making isort line length compatible with black
        - "--line-length=120"

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["-j8", "--ignore=E203,E501,P103", "--max-line-length=120"]
        additional_dependencies:
          - flake8-print
          - flake8-bugbear
          - flake8-loopy
          - flake8-super
          - flake8-django
          - flake8-comprehensions
          - pep8-naming

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          [
            "--exclude",
            "constants.py,**/management/**",
            "--skip",
            "B101",
          ]
