from db_data.models.assignment import *  # noqa
from db_data.models.assignment_file import *  # noqa
from db_data.models.attendance import *  # noqa
from db_data.models.base_user import *  # noqa
from db_data.models.lecture import *  # noqa
from db_data.models.material import *  # noqa
from db_data.models.score import *  # noqa
from db_data.models.student import *  # noqa
from db_data.models.workshop import *  # noqa
